### ISSUE TITLE
 [Distribution Detection:]   [############]Failed

### ISSUE THREAD

**Issue by rotv123** [IPTVUNION/iptvunion#15]
Please enter a password for your MySQL : *****
1. [password for your MySQL:]  [############mysqlshow: [Warning] Using a password on the command line interface can be insecure.
]Successful
2. [Distribution Detection:]   [############]Failed

Any fixing on this error?

**Comment by mickflix** [comment]
needs to be installed on fresh ubuntu 16.04 server

**Comment by mickflix** [comment]
also needs to be ran as root so you dont get the above error
